dist: bionic

addons:
  firefox: latest
  chrome: stable

language: node_js

node_js:
  - '12'
install:
  - npm install
script:
  - npm run build
  - npm run lint
  - npm run test:coverage
  - BASE_URL=http://127.0.0.1:8000 npx testcafe "chrome:headless,firefox:headless"
  - npm run codecov
